[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] Notebook coding_activity_2-4.ipynb is not trusted
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226) 10.07ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=515e2470-e5c4-ff20-8740-69584eef230f
[NotebookApp | INFO] Kernel started: 67d4ca61-cc45-4da9-b7b2-da6f78e2fb9b
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel 67d4ca61-cc45-4da9-b7b2-da6f78e2fb9b) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Starting buffering for 67d4ca61-cc45-4da9-b7b2-da6f78e2fb9b:ae3ef5fa51c1455189c94e28c2102999
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 67d4ca61-cc45-4da9-b7b2-da6f78e2fb9b
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] Kernel started: 18cfc4a0-9a40-4c89-8052-2f0b12586b42
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226) 9.98ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=0608f9de-ae82-8265-69d9-54b81fd9e977
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel 18cfc4a0-9a40-4c89-8052-2f0b12586b42) to 5.3 (client).
[NotebookApp | INFO] Starting buffering for 18cfc4a0-9a40-4c89-8052-2f0b12586b42:1e6697fe0b4446caad55bd9048862a38
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 18cfc4a0-9a40-4c89-8052-2f0b12586b42
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] Kernel started: 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226) 32.28ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=4f435618-ac95-3a57-5d36-9092777e2e9e
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
[NotebookApp | ERROR] Interrupting kernel
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
        result = validator.validate(os.path.join(self.notebook_dir, path))
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 220, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output
    
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
[NotebookApp | ERROR] Interrupting kernel
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
        result = validator.validate(os.path.join(self.notebook_dir, path))
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 220, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output
    
[NotebookApp | INFO] Starting buffering for 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3:0f5ff700390f419eaf28c1ba9847da4b
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.93): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.93) 3.03ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=f5d58a2e-552b-a674-a944-64c89e978f06
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
[NotebookApp | ERROR] Interrupting kernel
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
        result = validator.validate(os.path.join(self.notebook_dir, path))
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 220, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output
    
[NotebookApp | INFO] Starting buffering for 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3:644d9b4c6c9540e78c8dfb4de47ec08d
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 6f2c8383-bcf9-4ff1-a3ac-4c5070bd42d3
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226) 7.92ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=f00974be-34e4-123e-32d5-b6c261f96356
[NotebookApp | INFO] Kernel started: aa1aeffe-96dc-4c42-a7dc-55d441708461
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel aa1aeffe-96dc-4c42-a7dc-55d441708461) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
[NotebookApp | ERROR] Interrupting kernel
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
        result = validator.validate(os.path.join(self.notebook_dir, path))
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 220, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output
    
[NotebookApp | INFO] Starting buffering for aa1aeffe-96dc-4c42-a7dc-55d441708461:ecf0bfcfd6734e90802e00bd005bf70a
[NotebookApp | INFO] Kernel restarted: aa1aeffe-96dc-4c42-a7dc-55d441708461
[NotebookApp | INFO] Kernel restarted: aa1aeffe-96dc-4c42-a7dc-55d441708461
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel aa1aeffe-96dc-4c42-a7dc-55d441708461) to 5.3 (client).
[NotebookApp | INFO] Restoring connection for aa1aeffe-96dc-4c42-a7dc-55d441708461:ecf0bfcfd6734e90802e00bd005bf70a
[NotebookApp | INFO] Replaying 6 buffered messages
[NotebookApp | INFO] Starting buffering for aa1aeffe-96dc-4c42-a7dc-55d441708461:ecf0bfcfd6734e90802e00bd005bf70a
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel aa1aeffe-96dc-4c42-a7dc-55d441708461) to 5.3 (client).
[NotebookApp | INFO] Restoring connection for aa1aeffe-96dc-4c42-a7dc-55d441708461:ecf0bfcfd6734e90802e00bd005bf70a
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | ERROR] Timeout waiting for execute reply (30s).
[NotebookApp | ERROR] Interrupting kernel
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 48, in validate_notebook
        result = validator.validate(os.path.join(self.notebook_dir, path))
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/validator.py", line 220, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 597, in run_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output
    
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Starting buffering for aa1aeffe-96dc-4c42-a7dc-55d441708461:ecf0bfcfd6734e90802e00bd005bf70a
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: aa1aeffe-96dc-4c42-a7dc-55d441708461
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.10.226) 11.32ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=47cc157b-4fc3-7d20-d410-f706248e867b
[NotebookApp | INFO] Kernel started: 28f4ef09-e5bc-4f54-b0cf-34f819525a31
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel 28f4ef09-e5bc-4f54-b0cf-34f819525a31) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Starting buffering for 28f4ef09-e5bc-4f54-b0cf-34f819525a31:af5d9cd7af8f4ee1857ac6f35c1183c2
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 28f4ef09-e5bc-4f54-b0cf-34f819525a31
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://saladyear-monsterserial:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.11.179): No such file or directory: images/payroll.png
[NotebookApp | WARNING] 404 GET /notebooks/images/payroll.png (192.168.11.179) 8.16ms referer=https://saladyear-monsterserial-3000.codio.io/notebooks/coding_activity_2-4.ipynb?codioId=5dc6897c-1a8c-2880-262c-2020fecbcb9c
[NotebookApp | INFO] Kernel started: e79056b8-ac7f-4a00-8a22-b5ede85c8302
[NotebookApp | INFO] Adapting from protocol version 5.1 (kernel e79056b8-ac7f-4a00-8a22-b5ede85c8302) to 5.3 (client).
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | INFO] Saving file at /coding_activity_2-4.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/codio/workspace/coding_activity_2-4.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Starting buffering for e79056b8-ac7f-4a00-8a22-b5ede85c8302:2517087f1fd1405ea416fbca2198488a
[NotebookApp | CRITICAL] received signal 15, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: e79056b8-ac7f-4a00-8a22-b5ede85c8302
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/codio/workspace
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://nobodysponsor-elementengine:3000/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
